package org.acme.demo;


/**
 * Value type representing a postal address.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */

public record Address(
    // TODO: add record components from ontology
) {

    /** Compact constructor — validates all inputs. */
    public Address {
        // TODO: add validation
    }
}
