#!/usr/bin/env bash
# =================================================================
# Armstrong Stress Test Generation Script
# Auto-generated by StressTestScanner
# Source: src/main/java
# Findings: 41  (CRITICAL=10, HIGH=22)
# =================================================================
set -euo pipefail

# ── CRITICAL ──────────────────────────────────────────────
# BoundaryPattern in CrashRecovery.java
bin/jgen generate -t testing/stress-boundary -n CrashRecoveryStressTest -p org.acme

# QueuePattern in Proc.java
bin/jgen generate -t testing/stress-throughput -n ProcStressTest -p org.acme

# SharedStatePattern in ProcessRegistry.java
bin/jgen generate -t testing/stress-concurrency -n ProcessRegistryStressTest -p org.acme

# QueuePattern in StateMachine.java
bin/jgen generate -t testing/stress-throughput -n StateMachineStressTest -p org.acme

# QueuePattern in StressTestScanner.java
bin/jgen generate -t testing/stress-throughput -n StressTestScannerStressTest -p org.acme.dogfood.innovation

# SharedStatePattern in StressTestScanner.java
bin/jgen generate -t testing/stress-concurrency -n StressTestScannerStressTest -p org.acme.dogfood.innovation

# BoundaryPattern in StressTestScanner.java
bin/jgen generate -t testing/stress-boundary -n StressTestScannerStressTest -p org.acme.dogfood.innovation

# QueuePattern in Supervisor.java
bin/jgen generate -t testing/stress-throughput -n SupervisorStressTest -p org.acme

# BoundaryPattern in Supervisor.java
bin/jgen generate -t testing/stress-boundary -n SupervisorStressTest -p org.acme

# QueuePattern in VirtualThreadPatterns.java
bin/jgen generate -t testing/stress-throughput -n VirtualThreadPatternsStressTest -p org.acme.dogfood.concurrency

# ── HIGH ──────────────────────────────────────────────
# ListenerPattern in EventManager.java
bin/jgen generate -t testing/stress-cascade -n EventManagerStressTest -p org.acme

# TimeoutPattern in EventManager.java
bin/jgen generate -t testing/stress-timeout -n EventManagerStressTest -p org.acme

# LockContention in GathererPatterns.java
bin/jgen generate -t testing/stress-concurrency -n GathererPatternsStressTest -p org.acme.dogfood.core

# BoundaryPattern in GathererPatterns.java
bin/jgen generate -t testing/stress-boundary -n GathererPatternsStressTest -p org.acme.dogfood.core

# LockContention in LivingDocGenerator.java
bin/jgen generate -t testing/stress-concurrency -n LivingDocGeneratorStressTest -p org.acme.dogfood.innovation

# LockContention in ModernizationScorer.java
bin/jgen generate -t testing/stress-concurrency -n ModernizationScorerStressTest -p org.acme.dogfood.innovation

# LockContention in OntologyMigrationEngine.java
bin/jgen generate -t testing/stress-concurrency -n OntologyMigrationEngineStressTest -p org.acme.dogfood.innovation

# LockContention in Proc.java
bin/jgen generate -t testing/stress-concurrency -n ProcStressTest -p org.acme

# SharedStatePattern in Proc.java
bin/jgen generate -t testing/stress-concurrency -n ProcStressTest -p org.acme

# ListenerPattern in Proc.java
bin/jgen generate -t testing/stress-cascade -n ProcStressTest -p org.acme

# TimeoutPattern in Proc.java
bin/jgen generate -t testing/stress-timeout -n ProcStressTest -p org.acme

# SharedStatePattern in ProcLib.java
bin/jgen generate -t testing/stress-concurrency -n ProcLibStressTest -p org.acme

# SharedStatePattern in ProcRef.java
bin/jgen generate -t testing/stress-concurrency -n ProcRefStressTest -p org.acme

# SharedStatePattern in StateMachine.java
bin/jgen generate -t testing/stress-concurrency -n StateMachineStressTest -p org.acme

# LockContention in StressTestScanner.java
bin/jgen generate -t testing/stress-concurrency -n StressTestScannerStressTest -p org.acme.dogfood.innovation

# SharedStatePattern in StressTestScanner.java
bin/jgen generate -t testing/stress-concurrency -n StressTestScannerStressTest -p org.acme.dogfood.innovation

# ListenerPattern in StressTestScanner.java
bin/jgen generate -t testing/stress-cascade -n StressTestScannerStressTest -p org.acme.dogfood.innovation

# TimeoutPattern in StressTestScanner.java
bin/jgen generate -t testing/stress-timeout -n StressTestScannerStressTest -p org.acme.dogfood.innovation

# BoundaryPattern in StressTestScanner.java
bin/jgen generate -t testing/stress-boundary -n StressTestScannerStressTest -p org.acme.dogfood.innovation

# LockContention in Supervisor.java
bin/jgen generate -t testing/stress-concurrency -n SupervisorStressTest -p org.acme

# SharedStatePattern in Supervisor.java
bin/jgen generate -t testing/stress-concurrency -n SupervisorStressTest -p org.acme

# BoundaryPattern in Supervisor.java
bin/jgen generate -t testing/stress-boundary -n SupervisorStressTest -p org.acme

# ── MEDIUM ──────────────────────────────────────────────
# ListenerPattern in EventManager.java
bin/jgen generate -t testing/stress-cascade -n EventManagerStressTest -p org.acme

# TimeoutPattern in EventManager.java
bin/jgen generate -t testing/stress-timeout -n EventManagerStressTest -p org.acme

# TimeoutPattern in Proc.java
bin/jgen generate -t testing/stress-timeout -n ProcStressTest -p org.acme

# ListenerPattern in ProcLib.java
bin/jgen generate -t testing/stress-cascade -n ProcLibStressTest -p org.acme

# TimeoutPattern in ProcRef.java
bin/jgen generate -t testing/stress-timeout -n ProcRefStressTest -p org.acme

# TimeoutPattern in ProcSys.java
bin/jgen generate -t testing/stress-timeout -n ProcSysStressTest -p org.acme

# ListenerPattern in ProcessRegistry.java
bin/jgen generate -t testing/stress-cascade -n ProcessRegistryStressTest -p org.acme

# TimeoutPattern in StateMachine.java
bin/jgen generate -t testing/stress-timeout -n StateMachineStressTest -p org.acme

# TimeoutPattern in StressTestScanner.java
bin/jgen generate -t testing/stress-timeout -n StressTestScannerStressTest -p org.acme.dogfood.innovation

echo 'Stress test generation complete.'
echo 'Run: ./mvnw test -Dtest="*StressTest"'
