package io.github.seanchatmangpt.jotp.distributed;

import java.util.List;

/**
 * Service for generating globally unique, monotonically increasing sequence numbers across a
 * distributed cluster.
 *
 * <p>This interface provides distributed sequence number generation that guarantees uniqueness
 * across all nodes in the cluster, even in the presence of clock drift and network partitions.
 *
 * <p><strong>Key Properties:</strong>
 *
 * <ul>
 *   <li><strong>Global Uniqueness:</strong> No two sequence numbers are ever the same across the
 *       entire cluster
 *   <li><strong>Monotonicity:</strong> Sequence numbers are strictly increasing within a node and
 *       respect causal ordering across nodes
 *   <li><strong>High Performance:</strong> Local generation without coordination for most
 *       operations
 *   <li><strong>Resilience:</strong> Handles clock drift and node failures gracefully
 * </ul>
 *
 * <p><strong>Implementation Note:</strong> The default implementation uses Hybrid Logical Clock
 * (HLC) semantics, combining physical timestamps with logical counters to ensure ordering even when
 * clocks drift.
 *
 * <p><strong>Usage Example:</strong>
 *
 * <pre>{@code
 * // Create sequence service
 * var discovery = new StaticNodeDiscovery(...);
 * var seqService = GlobalSequenceService.create("node1", discovery);
 *
 * // Synchronize with peers on startup
 * seqService.synchronizeWithPeers(discovery.getHealthyNodes());
 *
 * // Generate globally unique sequence numbers
 * long seq1 = seqService.nextGlobalSeq();
 * long seq2 = seqService.nextGlobalSeq();
 * assert seq2 > seq1; // Monotonically increasing
 * }</pre>
 *
 * @see HybridLogicalClockSequenceService
 * @see NodeDiscovery
 */
public interface GlobalSequenceService {

    /**
     * Get the next globally unique sequence number.
     *
     * <p>Generates a sequence number that is guaranteed to be unique across all nodes in the
     * cluster and monotonically increasing relative to previous calls on this node.
     *
     * <p><strong>Cross-Node Ordering:</strong> If node A generates sequence number {@code s1} and
     * then sends a message to node B which generates {@code s2}, then {@code s2 > s1} (assuming the
     * message arrival provides causal linkage).
     *
     * @return a globally unique, monotonically increasing sequence number
     */
    long nextGlobalSeq();

    /**
     * Get the current high-water mark across all nodes.
     *
     * <p>Returns the highest sequence number this node is aware of, which may include numbers
     * generated by other nodes during synchronization. This can be used to detect if a node has
     * fallen behind or for conflict resolution.
     *
     * <p><strong>Consistency:</strong> This value is eventually consistent and may not reflect the
     * absolute highest sequence number in the cluster at this instant.
     *
     * @return the current high-water mark sequence number
     */
    long currentHighWaterMark();

    /**
     * Synchronize sequence state with peer nodes.
     *
     * <p>Should be called during node startup to ensure this node's sequence generator is aware of
     * the cluster's current state. This prevents sequence number collisions after node restarts.
     *
     * <p><strong>Implementation:</strong> This method queries peer nodes for their current
     * high-water marks and updates this node's state accordingly. If peers are unavailable, the
     * service may use persisted state or start from a safe baseline.
     *
     * @param peerNodes list of peer node names to synchronize with (must not be null, may be empty
     *     if no peers are available)
     * @throws NullPointerException if peerNodes is null
     */
    void synchronizeWithPeers(List<String> peerNodes);

    /**
     * Create a new GlobalSequenceService instance.
     *
     * <p>Creates a sequence service using the default Hybrid Logical Clock (HLC) implementation.
     * The service is initialized with the current time and ready to generate sequence numbers
     * immediately.
     *
     * <p><strong>Node ID Requirement:</strong> The node ID must be unique across the cluster. Using
     * duplicate node IDs will result in sequence number collisions.
     *
     * @param nodeId unique identifier for this node (must not be null or empty)
     * @param discovery the node discovery service for cluster membership (must not be null)
     * @return a new GlobalSequenceService instance
     * @throws NullPointerException if nodeId or discovery is null
     * @throws IllegalArgumentException if nodeId is empty
     */
    static GlobalSequenceService create(String nodeId, NodeDiscovery discovery) {
        return new HybridLogicalClockSequenceService(nodeId, discovery);
    }
}
