package io.github.seanchatmangpt.jotp.demo;

import io.github.seanchatmangpt.jotp.ApplicationController;
import org.assertj.core.api.WithAssertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * JUnit 5 test suite for Address.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */
@DisplayName("Address")
class AddressTest implements WithAssertions {

    @BeforeEach
    void setUp() {
        ApplicationController.reset();
    }

    // ── Construction ─────────────────────────────────────────────────────────

    @Test
    @DisplayName("should be constructed successfully")
    void shouldConstruct() {
        var address = new Address("123 Main St", "Springfield", "IL", "62701", "USA");
        assertThat(address).isNotNull();
        assertThat(address.street()).isEqualTo("123 Main St");
        assertThat(address.city()).isEqualTo("Springfield");
        assertThat(address.state()).isEqualTo("IL");
        assertThat(address.postalCode()).isEqualTo("62701");
        assertThat(address.country()).isEqualTo("USA");
    }

    // ── Equality & hash code ─────────────────────────────────────────────────

    @Test
    @DisplayName("equal instances should have equal hash codes")
    void equalInstancesHaveEqualHashCodes() {
        var address1 = new Address("123 Main St", "Springfield", "IL", "62701", "USA");
        var address2 = new Address("123 Main St", "Springfield", "IL", "62701", "USA");

        assertThat(address1).isEqualTo(address2);
        assertThat(address1.hashCode()).isEqualTo(address2.hashCode());
    }

    // ── toString ─────────────────────────────────────────────────────────────

    @Test
    @DisplayName("toString should include type name")
    void toStringShouldIncludeTypeName() {
        var address = new Address("123 Main St", "Springfield", "IL", "62701", "USA");
        assertThat(address.toString()).contains("Address");
    }
}
