package io.github.seanchatmangpt.jotp.demo;

import io.github.seanchatmangpt.jotp.ApplicationController;
import org.assertj.core.api.WithAssertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * JUnit 5 test suite for Person.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */
@DisplayName("Person")
class PersonTest implements WithAssertions {

    @BeforeEach
    void setUp() {
        ApplicationController.reset();
    }

    // ── Construction ─────────────────────────────────────────────────────────

    @Test
    @DisplayName("should be constructed successfully")
    void shouldConstruct() {
        var address = new Address("123 Main St", "Springfield", "IL", "62701", "USA");
        var person = new Person("John", "Doe", "john.doe@example.com", address);

        assertThat(person).isNotNull();
        assertThat(person.firstName()).isEqualTo("John");
        assertThat(person.lastName()).isEqualTo("Doe");
        assertThat(person.email()).isEqualTo("john.doe@example.com");
        assertThat(person.address()).isEqualTo(address);
    }

    // ── Equality & hash code ─────────────────────────────────────────────────

    @Test
    @DisplayName("equal instances should have equal hash codes")
    void equalInstancesHaveEqualHashCodes() {
        var address = new Address("123 Main St", "Springfield", "IL", "62701", "USA");
        var person1 = new Person("John", "Doe", "john.doe@example.com", address);
        var person2 = new Person("John", "Doe", "john.doe@example.com", address);

        assertThat(person1).isEqualTo(person2);
        assertThat(person1.hashCode()).isEqualTo(person2.hashCode());
    }

    // ── toString ─────────────────────────────────────────────────────────────

    @Test
    @DisplayName("toString should include type name")
    void toStringShouldIncludeTypeName() {
        var address = new Address("123 Main St", "Springfield", "IL", "62701", "USA");
        var person = new Person("John", "Doe", "john.doe@example.com", address);

        assertThat(person.toString()).contains("Person");
    }
}
