package io.github.seanchatmangpt.jotp.messaging.routing;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.function.Function;

/**
 * Splitter pattern (EIP).
 *
 * <p>Breaks a composite message into individual parts for independent processing. Each part is
 * sent as a separate message with metadata for correlation and sequencing.
 *
 * <p><strong>Pattern Semantics:</strong>
 * <ul>
 *   <li>Splits a composite message into N parts
 *   <li>Each part receives a unique sequence number (1-indexed)
 *   <li>All parts share the same correlation ID for tracking
 *   <li>Parts are immutable and thread-safe
 *   <li>Result list is unmodifiable to prevent accidental mutation
 * </ul>
 *
 * <p><strong>Use Cases:</strong>
 * <ul>
 *   <li>Processing individual items in a collection independently
 *   <li>Batch file processing (split lines, process each separately)
 *   <li>Order processing (split line items, fulfill each independently)
 *   <li>Partitioning for parallel processing
 * </ul>
 *
 * <p><strong>Thread Safety:</strong> Splitter methods are stateless and thread-safe.
 *
 * <p><strong>Reference:</strong> Enterprise Integration Patterns, Chapter 5: Splitter
 * (https://www.enterpriseintegrationpatterns.com/Splitter.html)
 */
public final class Splitter {

  private Splitter() {}

  /**
   * Part metadata: sequence number, total parts, correlation ID.
   *
   * @param correlationId the correlation ID (shared across all parts of a split)
   * @param sequenceNumber the sequence number (1-indexed)
   * @param totalParts the total number of parts
   */
  public record PartMetadata(UUID correlationId, int sequenceNumber, int totalParts) {
    /**
     * Validates metadata. Sequence number must be 1-indexed and in range [1, totalParts].
     */
    public PartMetadata {
      if (sequenceNumber < 1 || sequenceNumber > totalParts) {
        throw new IllegalArgumentException(
            "sequenceNumber must be 1-indexed and in range [1, " + totalParts + "]");
      }
    }
  }

  /**
   * A message part produced by splitting.
   *
   * @param <P> the payload type
   */
  public record MessagePart<P>(P payload, PartMetadata metadata) {
    /**
     * Returns a human-readable description of this part.
     *
     * @return description like "3/5 correlation: 550e8400-e29b-41d4-a716-446655440000"
     */
    public String describe() {
      return String.format(
          "%d/%d correlation: %s",
          metadata.sequenceNumber(), metadata.totalParts(), metadata.correlationId());
    }
  }

  /**
   * Splits a composite message into individual parts.
   *
   * <p>All parts are assigned a unique correlation ID generated by this method.
   *
   * @param message the composite message
   * @param splitter function that extracts parts from the message
   * @return unmodifiable list of message parts
   * @throws NullPointerException if message or splitter is null
   * @throws IllegalArgumentException if the splitter returns an empty list
   */
  public static <M, P> List<MessagePart<P>> split(
      M message, Function<M, List<P>> splitter) {
    return split(message, splitter, UUID.randomUUID());
  }

  /**
   * Splits a composite message into individual parts with an explicit correlation ID.
   *
   * @param message the composite message
   * @param splitter function that extracts parts from the message
   * @param correlationId the correlation ID to assign to all parts
   * @return unmodifiable list of message parts
   * @throws NullPointerException if message, splitter, or correlationId is null
   * @throws IllegalArgumentException if the splitter returns an empty list
   */
  public static <M, P> List<MessagePart<P>> split(
      M message, Function<M, List<P>> splitter, UUID correlationId) {
    Objects.requireNonNull(message, "message cannot be null");
    Objects.requireNonNull(splitter, "splitter cannot be null");
    Objects.requireNonNull(correlationId, "correlationId cannot be null");

    List<P> parts = splitter.apply(message);
    if (parts.isEmpty()) {
      throw new IllegalArgumentException("Splitter must return non-empty list");
    }

    List<MessagePart<P>> result = new ArrayList<>();
    int total = parts.size();
    for (int i = 0; i < total; i++) {
      result.add(
          new MessagePart<>(
              parts.get(i), new PartMetadata(correlationId, i + 1, total)));
    }

    return Collections.unmodifiableList(result);
  }

  /**
   * Partitions a message into fixed-size chunks.
   *
   * <p>Splits a collection into chunks of the given size, useful for batch processing.
   *
   * @param message the composite message
   * @param extractor function to extract the collection from the message
   * @param chunkSize the size of each chunk
   * @param builder function to construct a new message from a chunk
   * @return unmodifiable list of message parts
   * @throws NullPointerException if any parameter is null
   * @throws IllegalArgumentException if chunkSize <= 0
   */
  public static <M, P> List<MessagePart<M>> partition(
      M message,
      Function<M, List<P>> extractor,
      int chunkSize,
      Function<List<P>, M> builder) {
    Objects.requireNonNull(message, "message cannot be null");
    Objects.requireNonNull(extractor, "extractor cannot be null");
    Objects.requireNonNull(builder, "builder cannot be null");

    if (chunkSize <= 0) {
      throw new IllegalArgumentException("chunkSize must be positive");
    }

    List<P> items = extractor.apply(message);
    UUID correlationId = UUID.randomUUID();
    List<MessagePart<M>> result = new ArrayList<>();

    for (int i = 0; i < items.size(); i += chunkSize) {
      int end = Math.min(i + chunkSize, items.size());
      List<P> chunk = items.subList(i, end);
      M chunkMessage = builder.apply(chunk);
      int partNumber = (i / chunkSize) + 1;
      int totalParts = (items.size() + chunkSize - 1) / chunkSize;
      result.add(
          new MessagePart<>(
              chunkMessage, new PartMetadata(correlationId, partNumber, totalParts)));
    }

    return Collections.unmodifiableList(result);
  }
}
