apiVersion: v1
kind: ServiceAccount
metadata:
  name: jotp
  namespace: default
  labels:
    app: jotp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jotp
  namespace: default
  labels:
    app: jotp
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jotp
  namespace: default
  labels:
    app: jotp
subjects:
- kind: ServiceAccount
  name: jotp
  namespace: default
roleRef:
  kind: Role
  name: jotp
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jotp
  labels:
    app: jotp
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/healthz"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jotp
  labels:
    app: jotp
subjects:
- kind: ServiceAccount
  name: jotp
  namespace: default
roleRef:
  kind: ClusterRole
  name: jotp
  apiGroup: rbac.authorization.k8s.io
