package org.acme.dogfood.core;

import java.util.Optional;

/**
 * Pattern matching switch patterns — generated from {@code
 * templates/java/core/pattern-matching-switch.tera} and {@code
 * templates/java/core/instanceof-pattern.tera}.
 *
 * <p>Demonstrates Java 21+ exhaustive switch over sealed types, guarded patterns, record
 * destructuring, and {@code instanceof} pattern matching — the core of ggen's pattern-generator
 * capability for modern Java.
 *
 * <p><strong>Pattern contracts validated:</strong>
 *
 * <ul>
 *   <li>All sealed type variants are handled — compiler-enforced exhaustiveness.
 *   <li>Adding a new variant to the sealed type causes compile errors at every dispatch point.
 *   <li>Record destructuring binds component variables directly in the switch.
 *   <li>Guarded patterns ({@code when}) refine matches without nested {@code if} statements.
 * </ul>
 */
public final class PatternMatchingPatterns {

    private PatternMatchingPatterns() {}

    // =========================================================================
    // Domain: Payment methods (sealed hierarchy for pattern matching demos)
    // =========================================================================

    public sealed interface Payment
            permits Payment.CreditCard, Payment.BankTransfer, Payment.CryptoPay, Payment.Voucher {

        record CreditCard(String cardNumber, String holder, int cvv, double limit)
                implements Payment {}

        record BankTransfer(String iban, String bic, String accountName) implements Payment {}

        record CryptoPay(String walletAddress, String currency, double amount)
                implements Payment {}

        record Voucher(String code, double value, boolean singleUse) implements Payment {}
    }

    // =========================================================================
    // PATTERN 1: Exhaustive switch with record destructuring
    // BEFORE: if/else chains with instanceof checks and manual casts
    // AFTER:
    // =========================================================================

    /**
     * Describes a payment method. Exhaustive switch — compiler rejects unhandled variants.
     *
     * <p>Generated by {@code templates/java/core/pattern-matching-switch.tera}.
     */
    public static String describe(Payment payment) {
        return switch (payment) {
            case Payment.CreditCard(var num, var holder, _, var limit) ->
                    "Credit card %s (holder: %s, limit: %.2f)".formatted(maskCard(num), holder, limit);
            case Payment.BankTransfer(var iban, var bic, var name) ->
                    "Bank transfer via %s/%s (%s)".formatted(iban, bic, name);
            case Payment.CryptoPay(var wallet, var currency, var amount) ->
                    "%.4f %s to %s".formatted(amount, currency, maskWallet(wallet));
            case Payment.Voucher(var code, var value, var single) ->
                    "Voucher %s (%.2f, %s)".formatted(code, value, single ? "single-use" : "multi-use");
        };
    }

    // =========================================================================
    // PATTERN 2: Guarded patterns (when clause)
    // BEFORE: case X -> { if (condition) {...} else {...} }
    // AFTER:
    // =========================================================================

    /**
     * Classifies payment risk using guarded patterns. The {@code when} clause refines the match
     * without nesting if-statements inside the case body.
     */
    public static String riskLevel(Payment payment) {
        return switch (payment) {
            case Payment.CreditCard(_, _, _, var limit) when limit > 10_000 -> "HIGH";
            case Payment.CreditCard(_, _, _, var limit) when limit > 1_000 -> "MEDIUM";
            case Payment.CreditCard _ -> "LOW";
            case Payment.CryptoPay(_, _, var amount) when amount > 5_000 -> "HIGH";
            case Payment.CryptoPay _ -> "MEDIUM";
            case Payment.BankTransfer _ -> "LOW";
            case Payment.Voucher(_, var value, _) when value > 500 -> "MEDIUM";
            case Payment.Voucher _ -> "LOW";
        };
    }

    // =========================================================================
    // PATTERN 3: instanceof pattern matching (replaces cast)
    // BEFORE: if (obj instanceof String) { String s = (String) obj; ... }
    // AFTER:
    // =========================================================================

    /**
     * Validates and extracts a fee amount from any object using {@code instanceof} patterns.
     * Generated by {@code templates/java/core/instanceof-pattern.tera}.
     */
    public static Optional<Double> extractFee(Object obj) {
        if (obj instanceof Double d && d > 0) return Optional.of(d);
        if (obj instanceof Integer i && i > 0) return Optional.of(i.doubleValue());
        if (obj instanceof String s && !s.isBlank()) {
            try {
                double parsed = Double.parseDouble(s.strip());
                return parsed > 0 ? Optional.of(parsed) : Optional.empty();
            } catch (NumberFormatException _) {
                return Optional.empty();
            }
        }
        return Optional.empty();
    }

    // =========================================================================
    // PATTERN 4: Switch expression as value (not statement)
    // =========================================================================

    /**
     * Computes the processing fee for a payment method. Returns the fee as a double — switch is an
     * expression, not a statement.
     */
    public static double processingFee(Payment payment, double amount) {
        double rate =
                switch (payment) {
                    case Payment.CreditCard(_, _, _, var limit) when limit > 5000 -> 0.025;
                    case Payment.CreditCard _ -> 0.03;
                    case Payment.BankTransfer _ -> 0.001;
                    case Payment.CryptoPay(_, var currency, _) when "BTC".equals(currency) -> 0.01;
                    case Payment.CryptoPay _ -> 0.015;
                    case Payment.Voucher _ -> 0.0;
                };
        return amount * rate;
    }

    // =========================================================================
    // PATTERN 5: Null-safe switch (Java 21+ allows null as case)
    // =========================================================================

    /** Handles null-safe payment routing using {@code case null} in switch. */
    public static String route(Payment payment) {
        return switch (payment) {
            case null -> "rejected: null payment";
            case Payment.CreditCard _ -> "card-processor";
            case Payment.BankTransfer _ -> "sepa-gateway";
            case Payment.CryptoPay _ -> "crypto-exchange";
            case Payment.Voucher _ -> "voucher-service";
        };
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private static String maskCard(String num) {
        if (num == null || num.length() < 4) return "****";
        return "*".repeat(num.length() - 4) + num.substring(num.length() - 4);
    }

    private static String maskWallet(String addr) {
        if (addr == null || addr.length() < 8) return "****";
        return addr.substring(0, 4) + "..." + addr.substring(addr.length() - 4);
    }
}
