package io.github.seanchatmangpt.jotp.demo;

/**
 * Immutable monetary amount with currency.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */
public record Money(
        // TODO: add record components from ontology
        ) {

    /** Compact constructor — validates all inputs. */
    public Money {
        // TODO: add validation
    }
}
