package io.github.seanchatmangpt.jotp.demo;

import java.util.List;
import java.util.Optional;


/**
 * Business logic for Person management.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */

public interface PersonService {

    /**
     * Retrieve a Person by its identifier.
     *
     * @param id the entity identifier
     * @return the entity, or empty if not found
     */
    Optional<Person> findById(String id);

    /**
     * Retrieve all Person entities.
     *
     * @return an unmodifiable list of all entities
     */
    List<Person> findAll();

    /**
     * Persist a new Person.
     *
     * @param entity the entity to save
     * @return the saved entity (may carry server-assigned fields)
     */
    Person save(Person entity);

    /**
     * Remove a Person by its identifier.
     *
     * @param id the entity identifier
     */
    void deleteById(String id);
}
