package io.github.seanchatmangpt.jotp.order;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Customer order aggregate root.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */
public record Order(
        String id,
        String customerId,
        List<OrderItem> items,
        PaymentStatus paymentStatus,
        BigDecimal totalAmount,
        Instant createdAt,
        Instant updatedAt) {

    public Order {
        if (id == null || id.isBlank()) {
            id = UUID.randomUUID().toString();
        }
        if (customerId == null || customerId.isBlank()) {
            throw new IllegalArgumentException("customerId must not be null or blank");
        }
        items = items == null ? List.of() : List.copyOf(items);
        if (paymentStatus == null) {
            paymentStatus = PaymentStatus.pending();
        }
        if (totalAmount == null) {
            totalAmount = BigDecimal.ZERO;
        }
        var now = Instant.now();
        if (createdAt == null) {
            createdAt = now;
        }
        if (updatedAt == null) {
            updatedAt = now;
        }
    }

    /** Create a new order with generated ID and default timestamps. */
    public static Order create(String customerId, List<OrderItem> items) {
        return new Order(
                UUID.randomUUID().toString(),
                customerId,
                items,
                PaymentStatus.pending(),
                calculateTotal(items),
                Instant.now(),
                Instant.now());
    }

    private static BigDecimal calculateTotal(List<OrderItem> items) {
        return items.stream()
                .map(item -> item.unitPrice().multiply(BigDecimal.valueOf(item.quantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /** Return a new order with updated payment status. */
    public Order withPaymentStatus(PaymentStatus newStatus) {
        return new Order(id, customerId, items, newStatus, totalAmount, createdAt, Instant.now());
    }
}
