package io.github.seanchatmangpt.jotp.order;

import java.math.BigDecimal;

/**
 * A single line in a customer order.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */
public record OrderItem(String productId, String productName, int quantity, BigDecimal unitPrice) {

    /** Compact constructor — validates all inputs. */
    public OrderItem {
        if (productId == null || productId.isBlank()) {
            throw new IllegalArgumentException("productId must not be null or blank");
        }
        if (quantity <= 0) {
            throw new IllegalArgumentException("quantity must be positive");
        }
        if (unitPrice == null || unitPrice.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("unitPrice must be non-negative");
        }
    }
}
