package io.github.seanchatmangpt.jotp.order;

import java.util.List;
import java.util.Optional;


/**
 * Business logic for Order processing.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */

public interface OrderService {

    /**
     * Retrieve a Order by its identifier.
     *
     * @param id the entity identifier
     * @return the entity, or empty if not found
     */
    Optional<Order> findById(String id);

    /**
     * Retrieve all Order entities.
     *
     * @return an unmodifiable list of all entities
     */
    List<Order> findAll();

    /**
     * Persist a new Order.
     *
     * @param entity the entity to save
     * @return the saved entity (may carry server-assigned fields)
     */
    Order save(Order entity);

    /**
     * Remove a Order by its identifier.
     *
     * @param id the entity identifier
     */
    void deleteById(String id);
}
