package io.github.seanchatmangpt.jotp.order;

import org.assertj.core.api.WithAssertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * JUnit 5 test suite for PaymentStatus.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */
@DisplayName("PaymentStatus")
class PaymentStatusTest implements WithAssertions {

    // ── Construction ─────────────────────────────────────────────────────────

    @Test
    @DisplayName("should be constructed successfully")
    void shouldConstruct() {
        var pending = PaymentStatus.pending();
        var success = PaymentStatus.success("txn123");
        var failure = PaymentStatus.failure("insufficient funds");

        assertThat(pending).isNotNull().isInstanceOf(PaymentStatus.Pending.class);
        assertThat(success).isNotNull().isInstanceOf(PaymentStatus.Success.class);
        assertThat(failure).isNotNull().isInstanceOf(PaymentStatus.Failure.class);
    }

    // ── Equality & hash code ─────────────────────────────────────────────────

    @Test
    @DisplayName("equal instances should have equal hash codes")
    void equalInstancesHaveEqualHashCodes() {
        var success1 = PaymentStatus.success("txn123");
        var success2 = PaymentStatus.success("txn123");
        var failure1 = PaymentStatus.failure("insufficient funds");
        var failure2 = PaymentStatus.failure("insufficient funds");

        assertThat(success1).isEqualTo(success2);
        assertThat(success1.hashCode()).isEqualTo(success2.hashCode());

        assertThat(failure1).isEqualTo(failure2);
        assertThat(failure1.hashCode()).isEqualTo(failure2.hashCode());
    }

    // ── toString ─────────────────────────────────────────────────────────────

    @Test
    @DisplayName("toString should include type name")
    void toStringShouldIncludeTypeName() {
        var pending = PaymentStatus.pending();
        var success = PaymentStatus.success("txn123");
        var failure = PaymentStatus.failure("insufficient funds");

        assertThat(pending.toString()).contains("Pending");
        assertThat(success.toString()).contains("Success");
        assertThat(failure.toString()).contains("Failure");
    }
}
